### ISSUE TITLE
Does it support server mode?

### ISSUE THREAD

**Issue by paulo-raca** [horazont/aioopenssl#17]
Hello!

Thank you for this library, it looks like what I need!

For context, I'm playing with the idea of an HTTPS server that lazily produces certificate from ACME/Let's Encrypt when they are first accessed.

To do this I need to execute my code (a blocking asyncio callback) after the SSL handshake to and use the SNI and ALPN data to fetch/generate the correct certificate

However it is not completely clear how to do that:
- can the `post_handshake_callback` do that?
- Can `STARTTLSTransport` be used in server-mode? The tests always use it in client-mode 

Thank you!

**Comment by horazont** [comment]
No, server mode is currently not supported. An implementation was started in #5, but it was never finished.

**Comment by paulo-raca** [comment]
Thanks!

**Comment by matgnt** [comment]
Argh! Should we add this information to the Readme? It took me a while to find this closed issue containing this very relevant information.
