### ISSUE TITLE
Python3.7

### ISSUE THREAD

**Issue by delfick** [horazont/aioopenssl#7]
Hello,

Is version 0.3.2 meant to have this fix https://github.com/horazont/aioopenssl/commit/7839188552c78eefed99fdcae8849acd812075a6 ?

Cause it seems it doesn't...

Thanks.

**Comment by horazont** [comment]
Yupp. I managed to miss that. Even though it was one of the two reasons to make a release.

I think we’ll go straight for 0.4 at this point, I’ll try to do that this week.

**Comment by delfick** [comment]
cool, thanks :)

**Comment by horazont** [comment]
I released 0.4 just now. Let me know if there still are any issues.

**Comment by delfick** [comment]
yay! Thanks :)
